### ISSUE TITLE
Keep upjet and other dependencies up-to-date

### ISSUE THREAD

**Issue by ulucinar** [crossplane/upjet-provider-template#36]
### What problem are you facing?

Currently, the https://github.com/upbound/upjet dependency in this repo needs to be updated manually. We had better consume the latest upjet in this repo so that latest bug fixes and features in upjet are available here and development of a new upjet-based provider (when this repo is forked) does not start with a relatively older version of upjet.

### How could Upbound help solve your problem?

Can we employ a dependency management tool like renovate here also as we are already doing in the official provider repositories? Coupling this with https://github.com/upbound/upjet-provider-template/issues/34, we would also make sure that this repository stays compatible with the latest version of upjet.

**Comment by displague** [comment]
This issue should be updated to reflect that this is now a dependency on crossplane/upjet.

Updating to crossplane/upjet is more precarious now that it depends on go 1.21 while the rest of this project template hasn't been updated for 1.21.

Comparing against upbound/provider-aws, which is on 1.21, there are a number of improvements that can be made in the project. 

#54 was the last attempt to update upjet in this template project. It unearthed potential problems in how the Shared RPC vs CLI would be used, would these continue to be blockers for an upjet 1.1.0 update?

As a provider contributor using upjet-provider-template as a base for improvements, I'm stuck. Each semi-regular attempt to update leads to build errors which require a deep dive into the upbound/build, angryjet, crossplane-runtime, kubernetes-runtime, golangci-lint, go tooling, and go.
